name: Publish Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run -w @binvault/docs build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/public
          branch: public
          single-commit: true